### PR TITLE
fix: only allow whitelisted relayer account to send IBC relayer messages

### LINKED ISSUE #615: make sure ibc create client messages can't bypass whitelisted addresses by being wrapped (i.e with authz)

### PR DESCRIPTION
**Pull request by zale144**
## Description

----

Closes #615 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: server/ante/bypass_ibc_fee_decorator.go [hunk 1]
```diff
@@ -31,23 +31,23 @@ func NewBypassIBCFeeDecorator(nextAnte anteHandler, dk distrkeeper.Keeper, sk se
 // AnteHandle skips fee deduct and min gas price ante handlers for whitelisted relayer messages
 func (n BypassIBCFeeDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, next sdk.AnteHandler) (sdk.Context, error) {
 	// Check if the tx is from whitelisted relayer
-	whitelisted, err := n.isWhitelistedRelayer(ctx, tx.GetMsgs())
+	ibcWhitelisted, err := n.isIBCWhitelistedRelayer(ctx, tx.GetMsgs())
 	if err != nil {
-		// This error is not critical; just log and fall into the default fee handling
 		ctx.Logger().With("module", "BypassIBCFeeDecorator", "err", err).
 			Error("Failed to check if the tx is from the whitelisted relayer")
+		return ctx, fmt.Errorf("check if the tx is from the whitelisted relayer: %w", err)
```
Comment (omritoptix) [inline server/ante/bypass_ibc_fee_decorator.go:38]: why did we change to error? I think the previous log made more sense.

**Review by keruch — APPROVED** [review]

**Comment by mtsitrin** [comment]
@omritoptix  we wanted whitelisted to allow **client creation**
the on-going relaying over established channel should be permissionless

**Review by omritoptix — CHANGES_REQUESTED** [review]
as discussed we should reject mixed messages which contains IBC messages

File: server/ante/bypass_ibc_fee_decorator.go [hunk 2]
```diff
@@ -16,38 +18,60 @@ type anteHandler interface {
...
 	// The tx if not from the whitelisted relayer; proceed with the default fee handling
 	return n.nextAnte.AnteHandle(ctx, tx, simulate, next)
 }
 
-// isWhitelistedRelayer checks if all the messages in the transaction are from whitelisted IBC relayer
-func (n BypassIBCFeeDecorator) isWhitelistedRelayer(ctx sdk.Context, msgs []sdk.Msg) (bool, error) {
+// isIBCWhitelistedRelayer checks if all the messages in the transaction are from whitelisted IBC relayer
+func (n BypassIBCFeeDecorator) isIBCWhitelistedRelayer(ctx sdk.Context, msgs []sdk.Msg) (bool, error) {
 	// Check if the tx is from IBC relayer
 	if !IsIBCRelayerMsg(msgs) {
```
Comment (omritoptix) [inline server/ante/bypass_ibc_fee_decorator.go:76]: seems like we only enter this function if this condition is correct i.e `if ibcCount == totalMsgs` so not sure why should we check it twice.

File: server/ante/bypass_ibc_fee_decorator.go [hunk 3]
```diff
@@ -16,38 +18,60 @@ type anteHandler interface {
...
 
 	// The tx if not from the whitelisted relayer; proceed with the default fee handling
 	return n.nextAnte.AnteHandle(ctx, tx, simulate, next)
 }
 
-// isWhitelistedRelayer checks if all the messages in the transaction are from whitelisted IBC relayer
-func (n BypassIBCFeeDecorator) isWhitelistedRelayer(ctx sdk.Context, msgs []sdk.Msg) (bool, error) {
+// isIBCWhitelistedRelayer checks if all the messages in the transaction are from whitelisted IBC relayer
+func (n BypassIBCFeeDecorator) isIBCWhitelistedRelayer(ctx sdk.Context, msgs []sdk.Msg) (bool, error) {
 	// Check if the tx is from IBC relayer
```
Comment (omritoptix) [inline server/ante/bypass_ibc_fee_decorator.go:75]:
```suggestion
	// Check if all msgs are IBC msgs
```

**Review by omritoptix — DISMISSED** [review]
great job!
small nits.

File: server/ante/bypass_ibc_fee_decorator.go [hunk 4]
```diff
@@ -74,10 +98,56 @@ func (n BypassIBCFeeDecorator) isWhitelistedRelayer(ctx sdk.Context, msgs []sdk.
 		for _, signer := range signers {
 			_, ok := wlRelayersMap[signer.String()]
 			if !ok {
-				return false, nil
+				// if not a whitelisted relayer, we block them from sending the IBC relayer messages
+				return false, fmt.Errorf("signer %s is not a whitelisted relayer", signer.String())
```
Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:102]: Do we need now a recursive ante checker to unpack auth wrappers?

Comment (danwt) [reply server/ante/bypass_ibc_fee_decorator.go:102]: nvm I see it's there already

File: server/ante/bypass_ibc_fee_decorator.go [hunk 5]
```diff
@@ -16,38 +18,60 @@ type anteHandler interface {
...
+			return ctx, err
+		}
+		if ibcWhitelisted {
+			return next(ctx, tx, simulate)
+		}
+		return ctx, fmt.Errorf("not all signers whitelisted")
+	} else if ibcCount > 0 {
+		// mixed: some IBC and some non-IBC
+		return ctx, fmt.Errorf("mixed IBC and non-IBC messages in the same transaction not allowed")
 	}
```
Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:67]: Are you sure this is gonna let IBC gov proposals work as normal?

File: server/ante/bypass_ibc_fee_decorator.go [hunk 6]
```diff
@@ -16,38 +18,60 @@ type anteHandler interface {
...
 
 	// The tx if not from the whitelisted relayer; proceed with the default fee handling
 	return n.nextAnte.AnteHandle(ctx, tx, simulate, next)
 }
 
-// isWhitelistedRelayer checks if all the messages in the transaction are from whitelisted IBC relayer
-func (n BypassIBCFeeDecorator) isWhitelistedRelayer(ctx sdk.Context, msgs []sdk.Msg) (bool, error) {
+// isIBCWhitelistedRelayer checks if all the messages in the transaction are from whitelisted IBC relayer
+func (n BypassIBCFeeDecorator) isIBCWhitelistedRelayer(ctx sdk.Context, msgs []sdk.Msg) (bool, error) {
```
Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:74]: guess this func can now just return error, instead of bool and error (with Omris change)

File: server/ante/bypass_ibc_fee_decorator.go (hunk 4 above)
Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:102]:
```suggestion
				return false, fmt.Errorf("signer is not a whitelisted relayer: %s", signer.String())
```

File: server/ante/bypass_ibc_fee_decorator.go [hunk 7]
```diff
@@ -74,10 +98,56 @@ func (n BypassIBCFeeDecorator) isWhitelistedRelayer(ctx sdk.Context, msgs []sdk.
...
 		}
 	}
 
 	return true, nil
 }
+
+const maxDepth = 6
+
+// getAllFinalMsgs recursively extracts all final messages from possibly nested messages.
+func (n BypassIBCFeeDecorator) getAllFinalMsgs(ctx sdk.Context, msgs []sdk.Msg, depth int) ([]sdk.Msg, error) {
```
Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:113]: please describe depth in the docstring

File: server/ante/bypass_ibc_fee_decorator.go [hunk 8]
```diff
@@ -74,10 +98,56 @@ func (n BypassIBCFeeDecorator) isWhitelistedRelayer(ctx sdk.Context, msgs []sdk.
...
+	if depth >= maxDepth {
+		return nil, fmt.Errorf("found more nested msgs than permitted. Limit is : %d", maxDepth)
```
Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:115]: not more nested messages, but just a deeper depth

Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:115]:
```suggestion
		return nil, fmt.Errorf("found more nested msgs than permitted: limit is : %d", maxDepth)
```

File: server/ante/bypass_ibc_fee_decorator.go [hunk 9]
```diff
@@ -74,10 +98,56 @@ func (n BypassIBCFeeDecorator) isWhitelistedRelayer(ctx sdk.Context, msgs []sdk.
...
+		final = append(final, inner...)
+	}
+	return final, nil
+}
+
+// getInnerMsgs handles nested messages and returns the final messages contained inside them.
+func (n BypassIBCFeeDecorator) getInnerMsgs(ctx sdk.Context, msg sdk.Msg, depth int) ([]sdk.Msg, error) {
+	if depth >= maxDepth {
+		return nil, fmt.Errorf("found more nested msgs than permitted. Limit is : %d", maxDepth)
+	}
```
Comment (danwt) [inline server/ante/bypass_ibc_fee_decorator.go:133]: not needed I think

**Review by danwt — COMMENTED** [review]
Couple small code things.

Biggest question is if this breaks actual IBC gov props. Does it?

**Comment by omritoptix** [comment]
> Biggest question is if this breaks actual IBC gov props. Does it?

great point @danwt. don't think we actually need to prevent gov prop nested messages either way. @zale144

File: server/ante/bypass_ibc_fee_decorator.go (hunk 5 above)
Comment (zale144) [reply server/ante/bypass_ibc_fee_decorator.go:67]: if a governance proposal includes IBC messages and the signer is not whitelisted, the code will reject the transaction

**Review by omritoptix — APPROVED** [review]
