### PR TITLE
fix: dymint reset-state command not working

### LINKED ISSUE #287: `reset-state` command is broken
currently the `dymint reset-state` command uses `cometBFT` implementation, which deletes nothing in dymint case

### PR DESCRIPTION
**Pull request by srene**
This PR replaces tendermint reset-state command by a local command that enables removing only state. Tendermint command tries to remove db files with different names.

Closes #287 

# PR Standards

## Opening a pull request should be able to meet the following requirements

---

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: server/commands.go [hunk 1]
```diff
@@ -82,3 +85,49 @@ func ResetAll() *cobra.Command {
 
 	return resetAll
 }
+
+func ResetState() *cobra.Command {
+	// ResetStateCmd removes the database of the specified CometBFT core instance.
```
Comment (omritoptix) [inline server/commands.go:90]: wrong godoc. better put dymint :)

File: server/commands.go [hunk 2]
```diff
@@ -82,3 +85,49 @@ func ResetAll() *cobra.Command {
...
+		Use:     "reset-state",
+		Aliases: []string{"reset_state"},
+		Short:   "Remove all the data and WAL",
+		RunE: func(cmd *cobra.Command, args []string) (err error) {
+
+			config := server.GetServerContextFromCmd(cmd).Config
+			appdb := filepath.Join(config.DBDir(), "application.db")
+			dymintdb := filepath.Join(config.DBDir(), "dymint")
+			settlementdb := filepath.Join(config.DBDir(), "settlement")
+			snapshotsdb := filepath.Join(config.DBDir(), "snapshots")
```
Comment (omritoptix) [inline server/commands.go:101]: do we need to clear also the snapshot?

File: server/commands.go [hunk 3]
```diff
@@ -82,3 +85,49 @@ func ResetAll() *cobra.Command {
...
+			if cmtos.FileExists(appdb) {
```
Comment (omritoptix) [inline server/commands.go:102]: can probably have one function which accepts a path and do it vs writing the same code for all 4 paths.

File: server/commands.go (hunk 1 above)
Comment (srene) [reply server/commands.go]: fixed

File: server/commands.go (hunk 3 above)
Comment (srene) [reply server/commands.go]: done

File: server/commands.go (hunk 2 above)
Comment (srene) [reply server/commands.go]: by now, we keep the snapshots folder

File: server/commands.go [hunk 4]
```diff
@@ -82,3 +85,39 @@ func ResetAll() *cobra.Command {
...
+			}
+			return nil
+		},
+	}
+}
+
+func removePath(path string) error {
+	if cmtos.FileExists(path) {
+		if err := os.RemoveAll(path); err == nil {
+			fmt.Println("Removed application.db", "file", path)
```
Comment (mtsitrin) [inline server/commands.go:117]: `application.db` logging is probably wrong. `path` should be enough

Comment (srene) [reply server/commands.go]: fixed
